#!/bin/bash
# mirror-appcast.sh — make trkeybpm/appcast.xml a GENERATED byte-mirror of the
# canonical session-key/appcast.xml, and gate the canonical feed on the way past.
#
# WHY THIS EXISTS
# ---------------
# Session Key's Sparkle feed lives at session-key/appcast.xml. But every build up to
# and including b251 — which is the whole install base, because nothing above b251 has
# ever been published — bakes a DIFFERENT SUFeedURL:
#
#     b251 Info.plist SUFeedURL = https://tommy-rush.github.io/tr-apps-updates/trkeybpm/appcast.xml
#     (verified at RUNTIME: the app prints "updater feed: …/trkeybpm/appcast.xml")
#
# github.io 301s to update.tommy-rush.com, but the PATH survives, so
# /trkeybpm/appcast.xml and /session-key/appcast.xml are TWO SEPARATE FILES. A release
# published only into session-key/appcast.xml is invisible to every installed copy — it
# reaches ZERO users. SUFeedURL moved to /session-key/ at b256, so once a user takes ONE
# update off the trkeybpm feed they migrate to the canonical feed permanently.
#
# THE RULE THIS ENCODES
#   session-key/appcast.xml is CANONICAL and the only file a human edits.
#   trkeybpm/appcast.xml is GENERATED — never hand-edited — and must be byte-identical.
# Both feeds already point their enclosures at the session-key/ DIRECTORY, so an artifact
# is committed ONCE, into session-key/. Only the XML is mirrored.
#
# USAGE
#   tools/mirror-appcast.sh                 # regenerate the mirror from the working tree
#   tools/mirror-appcast.sh --check         # verify only; exit 1 if they differ (CI/publish gate)
#   tools/mirror-appcast.sh --from-head     # use HEAD:session-key/appcast.xml as the source,
#                                           # ignoring uncommitted staging edits
#   tools/mirror-appcast.sh --verify-sigs   # also EdDSA-verify EVERY enclosure (fail-closed)
#   flags combine, e.g. --check --verify-sigs
#
# NEVER touches SUPublicEDKey (it lives in the app, not in any appcast), never signs,
# never pushes, never contacts the live feed.
#
# IMPLEMENTATION NOTE (deliberate): every validation happens inside ONE python pass that
# parses the document once and never serializes attribute values back into delimited
# text. An earlier version emitted a TAB-separated url/sig/length table for the shell to
# re-read; character references (&#9; / &#10;) inside an attribute could fabricate extra
# rows and defeat both the pairing and the count check. Shell does copying and comparing
# only — it never re-parses feed content.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CANON="$REPO/session-key/appcast.xml"
MIRROR="$REPO/trkeybpm/appcast.xml"

CHECK_ONLY=0
FROM_HEAD=0
VERIFY_SIGS=0
for arg in "$@"; do
  case "$arg" in
    --check)       CHECK_ONLY=1 ;;
    --from-head)   FROM_HEAD=1 ;;
    --verify-sigs) VERIFY_SIGS=1 ;;
    -h|--help)     sed -n '1,36p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) echo "mirror-appcast: unknown argument '$arg'" >&2; exit 2 ;;
  esac
done

[ -f "$CANON" ] || { echo "FAIL: canonical feed missing: $CANON" >&2; exit 1; }

# ---- resolve the source bytes -------------------------------------------------
SRC="$(mktemp -t mirror-appcast-src)"
trap 'rm -f "$SRC" "${SRC}.new" 2>/dev/null || true' EXIT
if [ "$FROM_HEAD" = "1" ]; then
  git -C "$REPO" show HEAD:session-key/appcast.xml > "$SRC" \
    || { echo "FAIL: could not read HEAD:session-key/appcast.xml" >&2; exit 1; }
  echo "==> source: HEAD:session-key/appcast.xml (uncommitted staging edits ignored)"
else
  cp "$CANON" "$SRC"
  echo "==> source: working tree session-key/appcast.xml"
fi

# ---- locate sign_update if signature verification was requested ---------------
if [ "$VERIFY_SIGS" = "1" ]; then
  SIGN_UPDATE="${SIGN_UPDATE:-}"
  if [ -z "$SIGN_UPDATE" ]; then
    SIGN_UPDATE="$(find "$HOME/.openclaw/workspace/projects/tr-keybpm/.build/artifacts" \
                   -name sign_update -type f 2>/dev/null | head -1 || true)"
  fi
  if [ -z "$SIGN_UPDATE" ] || [ ! -x "$SIGN_UPDATE" ]; then
    echo "FAIL: --verify-sigs requested but sign_update was not found (set SIGN_UPDATE=/path)" >&2
    exit 1
  fi
else
  SIGN_UPDATE=""
fi

# ---- ONE parse, ALL gates, fail-closed ----------------------------------------
python3 - "$SRC" "$REPO" "$VERIFY_SIGS" "$SIGN_UPDATE" <<'PY' || exit 1
import base64, os, re, subprocess, sys
import xml.etree.ElementTree as ET
try:
    from email.utils import parsedate_to_datetime
except ImportError:
    parsedate_to_datetime = None

src, repo, verify_sigs, sign_update = sys.argv[1], sys.argv[2], sys.argv[3] == "1", sys.argv[4]
SPARKLE = "http://www.andymatuschak.org/xml-namespaces/sparkle"
PLACEHOLDER = re.compile(r"REPLACE[-_ ]?AT[-_ ]?PUSH|REPLACE[-_ ]?ON[-_ ]?PUSH|TBD|TODO|FIXME|XXX|PLACEHOLDER", re.I)

def fail(msg):
    sys.stderr.write("FAIL: %s\n" % msg)
    sys.exit(1)

raw = open(src, "rb").read()

# The document must be UTF-8. An earlier version scanned raw ASCII bytes for a DTD,
# which UTF-16 (or any other encoding) walks straight past while the parser still
# honours the declaration. Decoding first makes the DTD check encoding-proof.
if raw[:2] in (b"\xff\xfe", b"\xfe\xff") or raw[:4] in (b"\xff\xfe\x00\x00", b"\x00\x00\xfe\xff"):
    fail("the feed is UTF-16/UTF-32; this repository's appcasts are UTF-8 only")
try:
    text = raw.decode("utf-8")
except UnicodeDecodeError as e:
    fail("the feed is not valid UTF-8: %s" % e)
# REJECT a BOM rather than strip it. Stripping would validate transformed bytes while
# the mirror publishes the ORIGINAL bytes — e.g. a double BOM is malformed XML that a
# strip-then-parse gate would wave through. This repo's appcasts carry no BOM.
if text.startswith("\ufeff"):
    fail("the feed begins with a byte-order mark; this repository's appcasts must not")
declared = re.match(r'\s*<\?xml[^>]*encoding\s*=\s*["\']([^"\']+)["\']', text)
if declared and declared.group(1).lower() not in ("utf-8", "utf8"):
    fail("the feed declares encoding=%r; UTF-8 only" % declared.group(1))
# An appcast has no legitimate DTD. Refusing one on the DECODED text closes the entity
# attacks (XXE / billion-laughs) the stdlib parser would otherwise honour, with no
# defusedxml dependency on this repo.
if re.search(r"<!DOCTYPE|<!ENTITY", text, re.I):
    fail("the feed declares a DTD or ENTITY; appcasts must not")

try:
    root = ET.fromstring(text)
except ET.ParseError as e:
    fail("the feed is not parseable XML: %s" % e)

# Scan EXACTLY what Sparkle consumes: /rss/channel/item, and each item's DIRECT
# <enclosure> children (SUAppcast). Using iter() would also walk decoy items/enclosures
# buried elsewhere in the document — the gate would pass a feed Sparkle cannot use, or
# validate elements the client never reads.
channels = root.findall("channel") if root.tag == "rss" else []
if len(channels) != 1:
    fail("expected exactly one /rss/channel; found %d (root tag %r)" % (len(channels), root.tag))
items = channels[0].findall("item")
if not items:
    fail("the feed contains no /rss/channel/item elements")
stray_items = [e for e in root.iter("item") if e not in items]
if stray_items:
    fail("%d <item> element(s) outside /rss/channel that Sparkle would ignore — remove them"
         % len(stray_items))

# ---- gate: every item owns EXACTLY ONE non-placeholder pubDate ----------------
# Checked per ITEM on the parsed tree, so a multiline or entity-encoded placeholder
# cannot slip past the way a line-oriented grep allowed.
for idx, item in enumerate(items, 1):
    dates = item.findall("pubDate")
    title = (item.findtext("title") or "?").strip()
    if len(dates) != 1:
        fail("item %d (%s) has %d <pubDate> elements; exactly one is required" % (idx, title, len(dates)))
    value = "".join(dates[0].itertext()).strip()
    if not value:
        fail("item %d (%s) has an EMPTY <pubDate> — that is an unapproved staged item" % (idx, title))
    if PLACEHOLDER.search(value):
        fail("item %d (%s) has a placeholder <pubDate>: %r — that is an unapproved staged item"
             % (idx, title, value))
    # "not a placeholder" is not the same as "a date". Sparkle wants RFC 822, so parse it.
    if parsedate_to_datetime is None:
        fail("cannot validate pubDate: email.utils.parsedate_to_datetime unavailable")
    # parsedate_to_datetime alone is lenient (missing zone, trailing garbage). Require
    # the exact RFC 822 shape `date -R` emits, which is what Sparkle parses, THEN parse it.
    if not re.fullmatch(r"(Mon|Tue|Wed|Thu|Fri|Sat|Sun), \d{2} "
                        r"(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) "
                        r"\d{4} \d{2}:\d{2}:\d{2} [+-]\d{4}", value):
        fail("item %d (%s) <pubDate> is not in the `date -R` RFC 822 form "
             "('Wed, 08 Jul 2026 14:56:33 -0700'): %r" % (idx, title, value))
    try:
        parsedate_to_datetime(value)
    except (TypeError, ValueError) as e:
        fail("item %d (%s) has a <pubDate> that does not parse: %r (%s)"
             % (idx, title, value, e))
print("    %d item(s): each has exactly one valid RFC 822 pubDate, no placeholders" % len(items))

# ---- gate: every enclosure is https and carries a signature + length -----------
enclosures = [e for it in items for e in it.findall("enclosure")]
if not enclosures:
    fail("no <enclosure> is a direct child of a /rss/channel/item")
stray_enc = [e for e in root.iter("enclosure") if e not in enclosures]
if stray_enc:
    fail("%d <enclosure> element(s) Sparkle would ignore (not a direct child of a "
         "/rss/channel/item) — remove them" % len(stray_enc))
# Every enclosure must live under the canonical artifact prefix. Without this,
# --verify-sigs would resolve https://attacker.invalid/SessionKey-1.0.4-b251.zip to the
# LOCAL file of the same basename and verify THAT — proving nothing about what the URL
# actually serves. Pinning the prefix makes basename resolution sound: the URL can only
# name a file in this repository's own session-key/ directory.
# HARDCODED, deliberately not environment-overridable: an override would let a caller
# relax the very pin that makes basename resolution sound.
CANON_PREFIX = "https://update.tommy-rush.com/session-key/"
rows = []
for idx, enc in enumerate(enclosures, 1):
    # DO NOT .strip() the url. Sparkle sends the attribute as-is (percent-encoding a
    # trailing space to %20), so a stripped copy would let this gate verify a DIFFERENT
    # local file from the resource the client actually requests.
    url = enc.get("url") or ""
    if url != url.strip() or any(c.isspace() for c in url):
        fail("enclosure %d url contains whitespace: %r — the client would request a "
             "percent-encoded name that does not match any artifact" % (idx, url))
    for ch in ("%", "?", "#"):
        if ch in url:
            fail("enclosure %d url contains %r: %r — Sparkle drops the fragment and a query "
                 "is not part of the path, so the resource it FETCHES would differ from the "
                 "file this gate verifies. Keep artifact URLs literal." % (idx, ch, url))
    sig = enc.get("{%s}edSignature" % SPARKLE) or ""
    length = (enc.get("length") or "").strip()
    if not url.startswith("https://"):
        fail("enclosure %d has a non-https url: %r" % (idx, url))
    if not url.startswith(CANON_PREFIX):
        fail("enclosure %d is not under the canonical prefix %s: %r\n"
             "      (artifacts live in this repo's session-key/ directory only)"
             % (idx, CANON_PREFIX, url))
    tail = url[len(CANON_PREFIX):]
    if not tail or "/" in tail or tail in (".", ".."):
        fail("enclosure %d has a url that is not a single file under the prefix: %r" % (idx, url))
    if not sig:
        fail("enclosure %d (%s) has no sparkle:edSignature" % (idx, url))
    # `sign_update --verify` ignores stray non-Base64 characters; the SHIPPED client
    # (SUSignatures) decodes strictly, so a signature this gate accepts could still be
    # rejected on a customer's Mac. Validate it the way the client will.
    if sig != sig.strip() or any(c.isspace() for c in sig):
        fail("enclosure %d (%s) edSignature contains whitespace" % (idx, url))
    if not re.fullmatch(r"[A-Za-z0-9+/]{86}==", sig):
        fail("enclosure %d (%s) edSignature is not a strict base64 ed25519 signature "
             "(88 chars, A-Za-z0-9+/ then '=='): %r" % (idx, url, sig))
    try:
        if len(base64.b64decode(sig, validate=True)) != 64:
            raise ValueError("wrong decoded length")
    except Exception as e:
        fail("enclosure %d (%s) edSignature does not strictly decode to 64 bytes: %s"
             % (idx, url, e))
    if not length.isdigit():
        fail("enclosure %d (%s) has a non-numeric length: %r" % (idx, url, length))
    # `tail` is the single path segment already validated against the canonical prefix.
    # Resolving with it (never basename()) means the verified file is exactly the resource
    # the pinned URL names.
    rows.append((url, sig, int(length), tail))
print("    %d enclosure(s): all https, all carry an edSignature + a numeric length" % len(rows))

# ---- optional gate: EdDSA-verify EVERY enclosure. Fail-closed. ------------------
# Verification runs here, on the SAME in-memory rows produced by the parse. Nothing is
# serialized and re-read, so there is no pairing to desynchronise and no count to forge.
if verify_sigs:
    checked = 0
    # macOS is case-INSENSITIVE: `os.path.isfile` would happily resolve
    # `sessionkey-1.0.4-b251.zip` to the canonical `SessionKey-...zip`, while the HTTP path
    # is a DIFFERENT resource. Require an exact byte match against a real directory entry.
    try:
        entries = set(os.listdir(os.path.join(repo, "session-key")))
    except OSError as e:
        fail("cannot list session-key/: %s" % e)
    for url, sig, length, fname in rows:
        if fname not in entries:
            fail("enclosure filename %r does not exactly match any entry in session-key/ "
                 "(case matters: the HTTP path is case-sensitive even though this disk is not)"
                 % fname)
        art = os.path.join(repo, "session-key", fname)
        if not os.path.isfile(art):
            fail("enclosure not present in this checkout: session-key/%s\n"
                 "      (--verify-sigs is fail-closed; fetch the artifact or drop the item)" % fname)
        actual = os.path.getsize(art)
        if actual != length:
            fail("length mismatch for session-key/%s: feed says %d, file is %d" % (fname, length, actual))
        rc = subprocess.call([sign_update, "--verify", art, sig])
        if rc != 0:
            fail("EdDSA verify FAILED for session-key/%s" % fname)
        print("    edDSA OK + length OK: session-key/%s" % fname)
        checked += 1
    if checked != len(rows):
        fail("verified %d of %d enclosures — counts must match" % (checked, len(rows)))
    print("    EdDSA + length verified for ALL %d/%d enclosures" % (checked, len(rows)))
PY

# ---- do the mirror ------------------------------------------------------------
if [ "$CHECK_ONLY" = "1" ]; then
  [ -f "$MIRROR" ] || { echo "FAIL: mirror missing: $MIRROR" >&2; exit 1; }
  if cmp -s "$SRC" "$MIRROR"; then
    echo "==> CHECK PASS: trkeybpm/appcast.xml is a byte-exact mirror of the canonical feed"
    exit 0
  fi
  echo "FAIL: trkeybpm/appcast.xml has DRIFTED from session-key/appcast.xml" >&2
  diff "$MIRROR" "$SRC" >&2 || true
  echo "      run tools/mirror-appcast.sh to regenerate it" >&2
  exit 1
fi

mkdir -p "$(dirname "$MIRROR")"
cp "$SRC" "${SRC}.new"
mv "${SRC}.new" "$MIRROR"
cmp -s "$SRC" "$MIRROR" || { echo "FAIL: mirror did not land byte-identical" >&2; exit 1; }
echo "==> WROTE trkeybpm/appcast.xml (byte-identical mirror, $(wc -c < "$MIRROR" | tr -d ' ') bytes)"
echo "    idempotency: re-running --check on this tree must now PASS"
